### PR TITLE
remove endorsed jars during test run

### PR DESCRIPTION
**Pull request by gurunrao**
remove endorsed jars during test run
CI run post changes - https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck-grao/job/master/11/

Signed-off-by: Gurunandan <gurunandan.rao@oracle.com>

### CODE REVIEW

**Review by RohitKumarJain — APPROVED** [review]
Thanks for addressing this. 
LGTM.

**Comment by senivam** [comment]
@gurunrao after this PR we have failing build at https://ci.eclipse.org/jaxb-impl/job/TCK_jakarta_JAXB_run/6/console
Job is based on jaxb-tck Jenkinsfile directly taken from jaxb-tck master. Do you have any functional job which works after applying those changes in this PR or could you take a look what's wrong?

**Comment by senivam** [comment]
relates to #36 36

**Comment by gurunrao** [comment]
@senivam - the above PR also added missing content as required for documentation(more details here https://github.com/eclipse-ee4j/jaxb-tck/issues/19).
You can refer https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/ for functional job.

**Pull request merged**
