### PR TITLE
User guide update

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
This is still Work in Progress. I'm currently working on updating the Configuration Properties table.

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
Current [JAXB-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jaxb-tck/files/5168999/JAXB-TCK-Users-Guide.pdf)

**Comment by Tomas-Kraus** [comment]
PDF document after User guide update II commit: [JAXB-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jaxb-tck/files/5174820/JAXB-TCK-Users-Guide.pdf)
Finished rewriting of chapters 4 and 5.

Unfortunately there are formatting issues in T_able 4-1 Configuration Properties and Relevant Values_. This was already broken before my changes and I have no idea how to fix it except removing the table and changing the text as sequence of small chapters (one for each of the properties).

**Comment by Tomas-Kraus** [comment]
Properties table formating fixed: [JAXB-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jaxb-tck/files/5182973/JAXB-TCK-Users-Guide.pdf)
I removed the table and replaced it with list of small chapters for each of the properties.

**Review by gurunrao — COMMENTED** [review]
Initial changes looks good to me.
Please let us know when its complete.

**Comment by Tomas-Kraus** [comment]
@gurunrao It's complete.

**Comment by Tomas-Kraus** [comment]
[JAXB-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jaxb-tck/files/5195443/JAXB-TCK-Users-Guide.pdf)
Added some changes we discussed with @gurunrao today.

**Review by gurunrao — APPROVED** [review]
LGTM

**Pull request merged**
