### PR TITLE
#78: move from http to https for w3.org

### LINKED ISSUE #78: TCK Challenge for 16 tests failing due to www.w3.org redirect from http to https
The same tests were passing previous to the change from http to https.

For background see articles:
- https://www.w3.org/blog/2022/08/https-redirection-observations/#comment-117406
- https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/

The XML Binding 4.0 TCK tests that are failing now that previously passed before the www.w3.org started redirecting `http` requests to `https`.

For background see https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/ + https://www.w3.org/blog/2022/08/https-redirection-observations

Tests that are failing now that previously passed before the https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/ change:

1. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0001.jtr
2. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0002.jtr    
3. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0003.jtr 
4. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0001.jtr     
5. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0002.jtr 
6. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0003.jtr 
7. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0001.jtr
8. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0002.jtr
9. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0001.jtr
10. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0002.jtr
11. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0003.jtr
12. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0001.jtr
13. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0002.jtr
14. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0003.jtr
15. java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0001.jtr
16. java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0002.jtr 

[Failing test jtr files are archived here via failure_jtr.zip](https://github.com/eclipse-ee4j/jaxb-tck/files/9536776/failure_jtr.zip).

[GlassFish 7.0.0-M8](https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-M8.zip) also fails as well as per https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/175/

CC @alwin-joseph @gurunrao @arjantijms

### PR DESCRIPTION
**Pull request by lukasj**
fixes #78 hopefully - @gurunrao or @scottmarlow are you able to verify this change somehow? another way to verify this change can be to edit files updated in this PR by hand in official 4.0.0 TCK binary (there should be no need to build the TCK to verify this change)

### CODE REVIEW

**Comment by gurunrao** [comment]
I have started CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/jaxb-tck-guru/job/pull-80/3/ for the PR.

**Comment by scottmarlow** [comment]
I'll try this locally.  

Any suggestions for how to run a specify test folder?  With `ant` I always changed into the test folder before doing a `ant runclient`.  Is there a `configuration.jti` setting or command line option passed into `-runtests` (javatest.jar) command?

**Comment by lukasj** [comment]
reading https://github.com/eclipse-ee4j/jaxb-tck/issues/78#issuecomment-1245500725 again - it looks like `http://www.w3.org/2005/05/xmlmime` will have to be updated to `https` as well. Let's see if this particular change improves things first..

**Comment by scottmarlow** [comment]
> reading [#78 (comment)](https://github.com/eclipse-ee4j/jaxb-tck/issues/78#issuecomment-1245500725) again - it looks like `http://www.w3.org/2005/05/xmlmime` will have to be updated to `https` as well. Let's see if this particular change improves things first..

Which references to `http://www.w3.org/2005/05/xmlmime` need to change for those tests?  I don't see references directly in the failing tests to `http://www.w3.org/2005/05/xmlmime` unless I missed something.

Or in the XmlMimeType handling in the implementations like https://github.com/eclipse-ee4j/jaxb-ri?

**Comment by scottmarlow** [comment]
In case it helps, I started https://github.com/scottmarlow/jaxb-ri (fork of https://github.com/eclipse-ee4j/jaxb-ri) to update `http://www.w3.org/2005/05/xmlmime` references in there to `https`.  I'll try some testing of that change.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jaxb-ri/pull/1661 seems to resolve the 16 XML Binding TCK failures with WildFly.

**Comment by lukasj** [comment]
this did not help/is wrong

**Pull request closed without merging**
