### PR TITLE
javax-to-jakarta renames in source

### PR DESCRIPTION
**Pull request by dblevins**
Again an attempt to be helpful, but not versed in this TCK so unsure if this will even build.  Very open to direction on how to make this more actionable.

### CODE REVIEW

**Review by gurunrao — APPROVED** [review]

**Review by RohitKumarJain — COMMENTED** [review]
Copyright year update is required in the below files:

jaxb-tck/src/share/coverage/BindingXMLSchemaToJava.html
jaxb-tck/src/share/coverage/CustomizingXMLSchema.html
jaxb-tck/src/share/coverage/JavaTypes2XML.html

 Copyright (c) 2018 Oracle to  Copyright (c) 2018 Oracle, 2020

jaxb-tck/src/share/jttck/classes/com/sun/jaxb_tck/lib/JaxbTckScript.java
 
 Copyright (c) 2008, 2018 Oracle to Copyright (c) 2008, 2020 Oracle

jaxb-tck/tests/java2schema/CustomizedMapping/classes/XmlType/basetype/BaseType002d.java

 Copyright (c) 2005, 2018 Oracle to Copyright (c) 2005, 2020 Oracle

**Comment by dblevins** [comment]
@RohitKumarJain Note there are 8496 files that don't have 2020 in their copyright.  I'm happy to fix all of them, but would prefer to do it in a separate PR.

**Comment by dblevins** [comment]
@RohitKumarJain here's the PR for copyrights https://github.com/eclipse-ee4j/jaxb-tck/pull/28

**Comment by RohitKumarJain** [comment]
@dblevins , I guess there is some confusion, "you don't need to modify all the files, which is not even updated in the current year."

The copyright date should include the year when the content was first created and published on the site. Since the contents are constantly evolving it is common practice to use a notice that includes both the original creation date and the most recent date in which content was added or modified.

So you only need to update the copyright year in the most recently updated files. Hope it clarifies the intention of my review comment.

**Comment by RohitKumarJain** [comment]
@dblevins , Would like to know if you are still facing any issue? If we are good then can you please update the copyright year in the mentioned files in the PR comment above. Thanks

**Comment by gurunrao** [comment]
@Tomas-Kraus is it possible to merge above PR.
@RohitKumarJain will update copyright with new PR, once PR 27 is merged

**Pull request merged**
